# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(420, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.noticeBrowserLabel = QtWidgets.QLabel(self.centralwidget)
        self.noticeBrowserLabel.setGeometry(QtCore.QRect(4, 10, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.noticeBrowserLabel.setFont(font)
        self.noticeBrowserLabel.setObjectName("noticeBrowserLabel")
        self.noticeBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.noticeBrowser.setGeometry(QtCore.QRect(4, 30, 411, 192))
        self.noticeBrowser.setObjectName("noticeBrowser")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(4, 240, 411, 321))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setStyleSheet("/*style-dark*/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px solid #00BB9E;\n"
"    border-radius:5px;\n"
"    \n"
"}\n"
" \n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
" \n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: #D3D3D3;/*qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);*/\n"
"    border: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 80px;\n"
"    padding: 8px;\n"
"    color:#000000;\n"
"}\n"
" \n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 1.0 #00BB9E);\n"
" \n"
"}/**/\n"
" \n"
"QTabBar::tab:selected {\n"
"    border: 1px solid #00BB9E;\n"
"    /*border-bottom-color: #00BB9E;  same as pane color*/ \n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.loginTab = QtWidgets.QWidget()
        self.loginTab.setObjectName("loginTab")
        self.loginNameLabel = QtWidgets.QLabel(self.loginTab)
        self.loginNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.loginNameLabel.setObjectName("loginNameLabel")
        self.loginPwdLabel = QtWidgets.QLabel(self.loginTab)
        self.loginPwdLabel.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.loginPwdLabel.setObjectName("loginPwdLabel")
        self.loginAccessMethodLabel = QtWidgets.QLabel(self.loginTab)
        self.loginAccessMethodLabel.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.loginAccessMethodLabel.setObjectName("loginAccessMethodLabel")
        self.loginTipsLabel = QtWidgets.QLabel(self.loginTab)
        self.loginTipsLabel.setGeometry(QtCore.QRect(215, 130, 181, 16))
        self.loginTipsLabel.setObjectName("loginTipsLabel")
        self.loginName = QtWidgets.QLineEdit(self.loginTab)
        self.loginName.setGeometry(QtCore.QRect(80, 20, 311, 31))
        self.loginName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginName.setMaxLength(16)
        self.loginName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginName.setObjectName("loginName")
        self.loginPwd = QtWidgets.QLineEdit(self.loginTab)
        self.loginPwd.setGeometry(QtCore.QRect(80, 70, 311, 31))
        self.loginPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginPwd.setMaxLength(16)
        self.loginPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPwd.setObjectName("loginPwd")
        self.loginAccessMethod = QtWidgets.QComboBox(self.loginTab)
        self.loginAccessMethod.setGeometry(QtCore.QRect(80, 125, 87, 22))
        self.loginAccessMethod.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginAccessMethod.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginAccessMethod.setObjectName("loginAccessMethod")
        self.loginAccessMethod.addItem("")
        self.loginAccessMethod.addItem("")
        self.loginRememberMe = QtWidgets.QCheckBox(self.loginTab)
        self.loginRememberMe.setGeometry(QtCore.QRect(10, 180, 91, 19))
        self.loginRememberMe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginRememberMe.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginRememberMe.setObjectName("loginRememberMe")
        self.loginUnBindButton = QtWidgets.QPushButton(self.loginTab)
        self.loginUnBindButton.setGeometry(QtCore.QRect(355, 180, 41, 28))
        self.loginUnBindButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginUnBindButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginUnBindButton.setObjectName("loginUnBindButton")
        self.loginButton = QtWidgets.QPushButton(self.loginTab)
        self.loginButton.setGeometry(QtCore.QRect(110, 240, 231, 40))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginButton.setObjectName("loginButton")
        self.loginTrialButton = QtWidgets.QPushButton(self.loginTab)
        self.loginTrialButton.setGeometry(QtCore.QRect(355, 240, 41, 40))
        self.loginTrialButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginTrialButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginTrialButton.setObjectName("loginTrialButton")
        self.tabWidget.addTab(self.loginTab, "")
        self.rechargeTab = QtWidgets.QWidget()
        self.rechargeTab.setObjectName("rechargeTab")
        self.rechargeCardPwdLabel = QtWidgets.QLabel(self.rechargeTab)
        self.rechargeCardPwdLabel.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.rechargeCardPwdLabel.setObjectName("rechargeCardPwdLabel")
        self.rechargeLoginNameLabel = QtWidgets.QLabel(self.rechargeTab)
        self.rechargeLoginNameLabel.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.rechargeLoginNameLabel.setObjectName("rechargeLoginNameLabel")
        self.rechargeLoginName = QtWidgets.QLineEdit(self.rechargeTab)
        self.rechargeLoginName.setGeometry(QtCore.QRect(80, 20, 311, 31))
        self.rechargeLoginName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.rechargeLoginName.setMaxLength(16)
        self.rechargeLoginName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.rechargeLoginName.setObjectName("rechargeLoginName")
        self.rechargeCardPwd = QtWidgets.QLineEdit(self.rechargeTab)
        self.rechargeCardPwd.setGeometry(QtCore.QRect(80, 70, 311, 31))
        self.rechargeCardPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.rechargeCardPwd.setMaxLength(16)
        self.rechargeCardPwd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.rechargeCardPwd.setObjectName("rechargeCardPwd")
        self.rechargeButton = QtWidgets.QPushButton(self.rechargeTab)
        self.rechargeButton.setGeometry(QtCore.QRect(80, 240, 311, 40))
        self.rechargeButton.setObjectName("rechargeButton")
        self.tabWidget.addTab(self.rechargeTab, "")
        self.registerTab = QtWidgets.QWidget()
        self.registerTab.setObjectName("registerTab")
        self.registerLoginNameLabel = QtWidgets.QLabel(self.registerTab)
        self.registerLoginNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.registerLoginNameLabel.setObjectName("registerLoginNameLabel")
        self.registerLoginPwdLabel = QtWidgets.QLabel(self.registerTab)
        self.registerLoginPwdLabel.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.registerLoginPwdLabel.setObjectName("registerLoginPwdLabel")
        self.registerLoginSuperPwdLabel = QtWidgets.QLabel(self.registerTab)
        self.registerLoginSuperPwdLabel.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.registerLoginSuperPwdLabel.setObjectName("registerLoginSuperPwdLabel")
        self.registerCardPwdLabel = QtWidgets.QLabel(self.registerTab)
        self.registerCardPwdLabel.setGeometry(QtCore.QRect(10, 180, 71, 16))
        self.registerCardPwdLabel.setObjectName("registerCardPwdLabel")
        self.registerLoginName = QtWidgets.QLineEdit(self.registerTab)
        self.registerLoginName.setGeometry(QtCore.QRect(80, 20, 311, 31))
        self.registerLoginName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.registerLoginName.setMaxLength(16)
        self.registerLoginName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.registerLoginName.setObjectName("registerLoginName")
        self.registerLoginPwd = QtWidgets.QLineEdit(self.registerTab)
        self.registerLoginPwd.setGeometry(QtCore.QRect(80, 70, 311, 31))
        self.registerLoginPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.registerLoginPwd.setMaxLength(16)
        self.registerLoginPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerLoginPwd.setObjectName("registerLoginPwd")
        self.registerLoginSuperPwd = QtWidgets.QLineEdit(self.registerTab)
        self.registerLoginSuperPwd.setGeometry(QtCore.QRect(80, 120, 311, 31))
        self.registerLoginSuperPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.registerLoginSuperPwd.setMaxLength(16)
        self.registerLoginSuperPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerLoginSuperPwd.setObjectName("registerLoginSuperPwd")
        self.registerCardPwd = QtWidgets.QLineEdit(self.registerTab)
        self.registerCardPwd.setGeometry(QtCore.QRect(80, 180, 311, 31))
        self.registerCardPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.registerCardPwd.setMaxLength(16)
        self.registerCardPwd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.registerCardPwd.setObjectName("registerCardPwd")
        self.registerButton = QtWidgets.QPushButton(self.registerTab)
        self.registerButton.setGeometry(QtCore.QRect(80, 240, 311, 40))
        self.registerButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.registerButton.setObjectName("registerButton")
        self.tabWidget.addTab(self.registerTab, "")
        self.changePwdTab = QtWidgets.QWidget()
        self.changePwdTab.setObjectName("changePwdTab")
        self.changeLoginNameLabel = QtWidgets.QLabel(self.changePwdTab)
        self.changeLoginNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.changeLoginNameLabel.setObjectName("changeLoginNameLabel")
        self.changeLoginSuperPwdLabel = QtWidgets.QLabel(self.changePwdTab)
        self.changeLoginSuperPwdLabel.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.changeLoginSuperPwdLabel.setObjectName("changeLoginSuperPwdLabel")
        self.changeLoginPwdNewLabel = QtWidgets.QLabel(self.changePwdTab)
        self.changeLoginPwdNewLabel.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.changeLoginPwdNewLabel.setObjectName("changeLoginPwdNewLabel")
        self.changeLoginName = QtWidgets.QLineEdit(self.changePwdTab)
        self.changeLoginName.setGeometry(QtCore.QRect(80, 20, 311, 31))
        self.changeLoginName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.changeLoginName.setMaxLength(16)
        self.changeLoginName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.changeLoginName.setObjectName("changeLoginName")
        self.changeLoginSuperPwd = QtWidgets.QLineEdit(self.changePwdTab)
        self.changeLoginSuperPwd.setGeometry(QtCore.QRect(80, 70, 311, 31))
        self.changeLoginSuperPwd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.changeLoginSuperPwd.setMaxLength(16)
        self.changeLoginSuperPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changeLoginSuperPwd.setObjectName("changeLoginSuperPwd")
        self.changeLoginPwdNew = QtWidgets.QLineEdit(self.changePwdTab)
        self.changeLoginPwdNew.setGeometry(QtCore.QRect(80, 120, 311, 31))
        self.changeLoginPwdNew.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.changeLoginPwdNew.setMaxLength(16)
        self.changeLoginPwdNew.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changeLoginPwdNew.setObjectName("changeLoginPwdNew")
        self.changePwdButton = QtWidgets.QPushButton(self.changePwdTab)
        self.changePwdButton.setGeometry(QtCore.QRect(80, 240, 311, 40))
        self.changePwdButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.changePwdButton.setObjectName("changePwdButton")
        self.tabWidget.addTab(self.changePwdTab, "")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "蘑菇助手V1.0.0"))
        self.noticeBrowserLabel.setText(_translate("LoginWindow", "公告"))
        self.loginNameLabel.setText(_translate("LoginWindow", "用户名"))
        self.loginPwdLabel.setText(_translate("LoginWindow", "用户密码"))
        self.loginAccessMethodLabel.setText(_translate("LoginWindow", "访问方式"))
        self.loginTipsLabel.setText(_translate("LoginWindow", "网络错误时请切换访问方式"))
        self.loginAccessMethod.setItemText(0, _translate("LoginWindow", "WinHttp"))
        self.loginAccessMethod.setItemText(1, _translate("LoginWindow", "WinInet"))
        self.loginRememberMe.setText(_translate("LoginWindow", "记住我"))
        self.loginUnBindButton.setText(_translate("LoginWindow", "解绑"))
        self.loginButton.setText(_translate("LoginWindow", "登录"))
        self.loginTrialButton.setText(_translate("LoginWindow", "试用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loginTab), _translate("LoginWindow", "用户登录"))
        self.rechargeCardPwdLabel.setText(_translate("LoginWindow", "卡密"))
        self.rechargeLoginNameLabel.setText(_translate("LoginWindow", "用户名"))
        self.rechargeButton.setText(_translate("LoginWindow", "充值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rechargeTab), _translate("LoginWindow", "用户充值"))
        self.registerLoginNameLabel.setText(_translate("LoginWindow", "用户名"))
        self.registerLoginPwdLabel.setText(_translate("LoginWindow", "用户密码"))
        self.registerLoginSuperPwdLabel.setText(_translate("LoginWindow", "超级密码"))
        self.registerCardPwdLabel.setText(_translate("LoginWindow", "卡密"))
        self.registerButton.setText(_translate("LoginWindow", "注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.registerTab), _translate("LoginWindow", "用户注册"))
        self.changeLoginNameLabel.setText(_translate("LoginWindow", "用户名"))
        self.changeLoginSuperPwdLabel.setText(_translate("LoginWindow", "超级密码"))
        self.changeLoginPwdNewLabel.setText(_translate("LoginWindow", "新密码"))
        self.changePwdButton.setText(_translate("LoginWindow", "修改密码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.changePwdTab), _translate("LoginWindow", "修改密码"))
